default: &default
  adapter: mysql2
  username: newuser
  password: password
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
   <<: *default
   database: library_development

test:
  <<: *default
  database: library_test

production:
  <<: *default
  database: library_production